import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "./fonts/Pretendard-Regular.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "전남대불산학융합원 도면 및 검사관리 솔루션",
  description: "Generated by create next app",
};

export default function RootLayout({
     children,
   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ko">
      <body className={`${pretendard.variable}`}>
      {children}
      </body>
      </html>
  );
}
