import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Container from "./components/Container";
import api from "@/lib/api";

const pretendard = localFont({
  src: "./fonts/Pretendard-Regular.woff",
  variable: "--font-pretendard-sans",
});

export const metadata: Metadata = {
  title: "전남대불산학융합원 도면 및 검사관리 솔루션",
  description: "Generated by create next app",
};

export default function RootLayout({
     children,
   }: Readonly<{
  children: React.ReactNode;
}>) {
  // const formData = new FormData()
  // formData.append('managerUuid', '66e7e19f07cd1')
  // const response = await api.post(`/admin/adminInfo.php`, formData)
  return (
      <html lang="ko">
      <body className={`${pretendard.variable}`}>
        {/* <Container info={response?.data}> */}
            {children}
        {/* </Container> */}
      </body>
      </html>
  );
}
